baseURL = 'https://filiposki54.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-coder"
publishDir = "public"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 1